/* preprocessor instructions to include standard input/output functions, functions for number conversion and storage allocation,*/
#include <stdio.h> 
#include <stdlib.h>

int main(){
	/* declare file pointer ps */
	FILE* ps; 
	/* popen opens a process by creating a pipe, forking, and invoking the 
	shell. popen's first argument is a shell command line, in this case ps.
	popen's second argument is the letter r which designates the generated
	stream as for reading.
	ps displays the currently running processes. -U root option displays every 
	process running as root. -o option offers a way to specify individual output
	columns as a single argument in the form of a comma-separated list. Within the
	comma-separated list pid displays the process id in the first column and args h
	displays the command with all its arguments as a string in human readable form.
    The stream generated by popen is assigned to the ps file pointer*/
	ps = popen("ps -U root -o pid,args h", "r");
	
	/* declare a character array of 80 elements that will be used to display
	each process currently running as root */
	char output[80];
	// declare and initialise an integer variable for line number
	int line_num = 0;

	/* fgets reads from ps file pointer (which is a pointer to the stream
	we are reading) a line at a time, storing each process pid and command line 
	within the output array variable, up to a size of 80 characters before starting 
	a new line.
	while loop will iterate until fgets retuns null, i.e. the stream has all
	been read.
	*/
	while(fgets(output, 80, ps) != NULL) {
    	/* display the pre-incremented line number and the current iteration's
    	pid and command line string stored in output */
    	printf("%d: %s", ++line_num, output);
	}
	/* pclose closes the stream assigned to the ps file pointer*/
	pclose(ps);
	// return 0 to terminate the program
	return 0;
}